# Generated by Django 5.2.8 on 2025-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="tel_number",
            new_name="phone",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="profession",
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
