# Generated by Django 5.2.8 on 2025-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactlist", "0002_rename_tel_number_contact_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="address",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(default="uaenorth", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="hospital",
            field=models.CharField(default="Unknown Hospital", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="specialization",
            field=models.CharField(default="General", max_length=100),
            preserve_default=False,
        ),
    ]
