# Generated by Django 5.2.8 on 2025-11-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactlist", "0003_remove_contact_address_remove_contact_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialty", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("hospital", models.CharField(max_length=100)),
                ("fee", models.IntegerField()),
                ("rating", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
